[build]
  command = "npm run build:prod"
  publish = "dist/app-medic-aifront"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.development.environment]
  NODE_ENV = "development"

[context.qa.environment]
  NODE_ENV = "qa"
